### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosify#44]
Create a PyPI release, as suggested by @danmichaelo in #43.

**Comment by nichtich** [comment]
yes, please.

**Comment by nichtich** [comment]
Please also make usable as Python module so it can be integrated for instance in <https://github.com/gbv/mc2skos>, e.g.:

```python:
import skosify
skosify.Skosify(**options).skosify(graph)
```

**Comment by osma** [comment]
@nichtich Hmm, right. This has indeed stalled for quite a while. I will look into it.

**Comment by nichtich** [comment]
The instructions at https://github.com/NatLibFi/Skosify/wiki/Getting-Started are also outdated (mentioning SVN instead of GitHub, `skosify.py` instead of `./skosify/skosify.py`...

**Comment by osma** [comment]
I just released Skosify 2.1.0 [here on GitHub](https://github.com/NatLibFi/Skosify/releases/tag/v2.1.0) and also [on PyPI](https://pypi.org/project/skosify/2.1.0/). Closing this issue.
