### ISSUE TITLE
Parsing problem with ids starting with a digit

### ISSUE THREAD

**Issue by wyrlwind** [NatLibFi/Skosify#48]
i've a SKOS file I want to process with Skosify,but when reading the file there a parsing error. 

we have the following  description

```
@prefix :      <https://test.org/vocab/MainOntology#> .

:3DGeologicalModel  a    skos:Concept ;
        skos:broader     :GeologicalInterpretation ;
        skos:definition  "3D geological model"@en ;
        skos:inScheme    :MainOntologyVocabulary ;
        skos:prefLabel   "3D geological model"@en .
```

the problem comes from the ID `3DGeologicalModel` that starts with a number, if we replace it by `ThreeDGeologicalModel` everything works fine.

**Comment by osma** [comment]
Parsing is handled by the rdflib library, not Skosify itself. Please try installing the newest rdflib version from PyPI (e.g. using pip install).


If you still experience this problem, please tell your Python and rdflib versions and the exact error messages you are getting.
