### ISSUE TITLE
suppress copying of skos:relatedMatch to skos:related

### ISSUE THREAD

**Issue by babslgam** [NatLibFi/Skosify#53]
hi,
is there an option to suppress the creation of skos:related from skos:relatedMatch?
thanks,
barbara

**Comment by osma** [comment]
Disabling enrich_mappings should do what you want. I.e. use `--no-enrich-mappings` on the command line or set `enrich_mappings=false` in the config file.

**Comment by osma** [comment]
Closed due to inactivity.
