### ISSUE TITLE
No Concept Scheme found because of http**S**://... #ConceptScheme

### ISSUE THREAD

**Issue by Kordishal** [NatLibFi/Skosify#57]
In all of the EAGLE Vocabularies Skosify tells me that there is no Concept Scheme. 

The reason appears to be, that they use http**S**:// for the skos name space. Or at least this is the only difference I could find.

Would it be possible for skosify to accept both versions?

https://www.eagle-network.eu/voc/statepreserv.rdf
https://www.eagle-network.eu/voc/writing.rdf
https://www.eagle-network.eu/voc/typeins.rdf

    Don't know what to do with type https://www.w3.org/2004/02/skos/core#ConceptScheme
    Don't know what to do with type https://www.w3.org/2004/02/skos/core#Concept
    No skos:ConceptScheme or owl:Ontology found. Using namespace auto-detection for creating concept scheme.

**Comment by osma** [comment]
In RDF, a `https://` URI is different from a `http://` URI. The W3C SKOS spec says that the SKOS namespace is `http://www.w3.org/2004/02/skos/core#` with `http://`, not `https://`. So the data is simply broken and even if Skosify accepted it, other SKOS-aware tools wouldn't understand it.

I guess it would be possible for Skosify to fix this by changing all SKOS-but-with-https URIs to regular SKOS URIs, but if it's only a problem for a handful of data sets and they are all from the same source, I think it makes more sense to fix it in those data sets directly.

**Comment by Kordishal** [comment]
Thanks for the quick answer. This makes a lot of sense. I will contact EAGLE on this issue.
