### ISSUE TITLE
PyPI package issue with Ubuntu 18.04

### ISSUE THREAD

**Issue by devseppala** [NatLibFi/Skosify#67]
Installed Skosify on Ubuntu 18.04 using:

sudo pip3 install --upgrade skosify

and running skosify gives this error message in the log file:

Traceback (most recent call last):
  File "/usr/local/bin/skosify", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/skosify/cli.py", line 209, in main
    config.read_file(options.config)
  File "/usr/local/lib/python3.6/dist-packages/skosify/config.py", line 90, in read_file
    expand_mapping_target(self.namespaces, val)
  File "/usr/local/lib/python3.6/dist-packages/skosify/config.py", line 154, in expand_mapping_target
    ret.append((expand_curielike(namespaces, v), inverse))
  File "/usr/local/lib/python3.6/dist-packages/skosify/config.py", line 135, in expand_curielike
    return URIRef(namespaces[ns].term(localpart))
AttributeError: 'URIRef' object has no attribute 'term'

Perhaps the PyPI package just needs some updating. The version from Github repository works fine.

**Comment by danmichaelo** [comment]
The last PyPI release (2.0.1) was in Nov 2017, so a new PyPI release would indeed be good since there's been quite some changes since then.

**Comment by osma** [comment]
@nichtich Would you mind giving me a maintainer role for Skosify on pypi.org? My PyPI user name is "osma". I could try to set up automated deployment to PyPI via Travis CI, like I've done for other projects. It makes it a lot easier to do releases.

**Comment by nichtich** [comment]
@osma ok, done!

**Comment by osma** [comment]
I just released Skosify 2.1.0 [here on GitHub](https://github.com/NatLibFi/Skosify/releases/tag/v2.1.0) and also [on PyPI](https://pypi.org/project/skosify/2.1.0/). Closing this issue. Please reopen if you still have the same problem after upgrading @devseppala !
