### ISSUE TITLE
Skosify does not work with rdflib 6.0.0

### ISSUE THREAD

**Issue by Code42Cate** [NatLibFi/Skosify#86]
Hey, 

the skosify cli and Python library both don't work for some reason with rdflib 6.0.0. This error gets thrown:
![image](https://user-images.githubusercontent.com/26679776/131101589-dc1ad528-bfb1-4b62-afad-270fc3cb490c.png)

The last version that I managed to make it work with is this commit: https://github.com/RDFLib/rdflib/commit/26dba21d0562fdc8141cf758c61e14dd9edfa972

I am not sure what the problem is, but at least excluding rdflib 6.0.0 in the skosify setup would fix it for now. Let me know if I should make a PR or if you need more information to debug this:)

Cheers, Jonas

**Comment by osma** [comment]
Thanks for the report! It seems like the RDF namespace has changed a bit in that rdflib release.
